# Generated by Django 3.1.3 on 2020-11-14 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "guid",
                    models.CharField(
                        help_text="A unique identifier, defined by MX",
                        max_length=256,
                        unique=True,
                        verbose_name="MX Atrium guid",
                    ),
                ),
                (
                    "is_disabled",
                    models.BooleanField(
                        help_text="True if you want the user disabled, false otherwise",
                        verbose_name="MX Atrium is_disabled",
                    ),
                ),
                (
                    "account_user",
                    models.OneToOneField(
                        help_text="Application User this MX Atrium User belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
