# Generated by Django 3.1.3 on 2020-11-15 23:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_auto_20201114_1903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
