---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strawberry
  namespace: strawberry
spec:
  selector:
    matchLabels:
      app: strawberry
  replicas: 2
  template:
    metadata:
      labels:
        app: strawberry
    spec:
      containers:
        - name: strawberry
          image: colecrtr/strawberry:{{ STRAWBERRY_TAG }}
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret-key
            - name: DJANGO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-name
            - name: DJANGO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-user
            - name: DJANGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-password
            - name: DJANGO_DATABASE_HOST
              value: "127.0.0.1"
            - name: MX_ATRIUM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mx-atrium
                  key: api-key
            - name: MX_ATRIUM_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mx-atrium
                  key: client-id
          command:
            - "/bin/sh"
            - "-c"
          args:
            - |
              trap "touch /tmp/sidecar/terminate" EXIT
              uvicorn project.asgi:application --host=0.0.0.0 --port=8000
          volumeMounts:
            - name: tmp-sidecar
              mountPath: /tmp/sidecar
              readOnly: true
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17-alpine
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              /cloud_sql_proxy -instances=colecarter:us-central1:colecarter=tcp:5432&
              while ! test -f /tmp/sidecar/terminate; do
                sleep 5
              done
              echo "Sidecar termination flag found"
              exit 0
          volumeMounts:
            - name: tmp-sidecar
              mountPath: /tmp/sidecar
              readOnly: true
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: tmp-sidecar
          emptyDir: {}
