---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: strawberry-database-migration-
  namespace: strawberry
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: strawberry
          image: colecrtr/strawberry:{{ STRAWBERRY_TAG }}
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret-key
            - name: DJANGO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-name
            - name: DJANGO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-user
            - name: DJANGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-password
            - name: DJANGO_DATABASE_HOST
              value: "localhost"
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 2s
              trap "touch /tmp/sidecar/terminate" EXIT
              python manage.py migrate --no-input
          volumeMounts:
            - name: tmp-sidecar
              mountPath: /tmp/sidecar
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command: ["/bin/sh", "-c"]
          args:
            - |
              /cloud_sql_proxy -instances=colecarter:us-central1:colecarter=tcp:5432 & CHILD_PID=$!
              (
                while true;
                  do if [[ -f "/tmp/sidecar/terminate" ]]; then
                    kill $CHILD_PID;
                    echo "Killed $CHILD_PID because the main container terminated";
                  fi;
                  sleep 1s;
                done;
              ) &
              wait $CHILD_PID;
              if [[ -f "/tmp/sidecar/terminate" ]]; then exit 0; echo "Exiting"; fi;
          volumeMounts:
            - name: tmp-sidecar
              mountPath: /tmp/sidecar
              readOnly: true
          securityContext:
            runAsNonRoot: true
      restartPolicy: Never
      volumes:
        - name: tmp-sidecar
          emptyDir: {}
  backoffLimit: 2
