---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: strawberry-database-migration-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: strawberry
          image: colecrtr/strawberry:{{ STRAWBERRY_TAG }}
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret-key
            - name: DJANGO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-name
            - name: DJANGO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-user
            - name: DJANGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database-password
          command:
            - "python"
            - "manage.py"
            - "migrate"
            - "--no-input"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.18
          command:
            - "/cloud_sql_proxy"
            - "-instances=colecarter:us-central1:colecarter=tcp:5432"
          securityContext:
            runAsNonRoot: true
      restartPolicy: Never
  backoffLimit: 2
